### ISSUE TITLE
Comment section for each publication

### ISSUE THREAD

**Issue by remiolsen** [NationalGenomicsInfrastructure/ngipubs#26]
Would help greatly for tricky to classify publications and with collective decision-making. Something like:

```
<2018-10-31 15:00><remi-andre.olsen@...> This one should be discarded
<2018-10-31 15:05><someoneelse@...> No it shouldn't, because ...
[Add comment]
```

**Comment by ewels** [comment]
![nice!](https://www.gifimage.net/wp-content/uploads/2018/11/ooh-yeah-gif-5.gif)
